# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAPIgBwDjojDbO4FTj3hIxDNbmpjUEMIBx-Mguple";
    path = fetchzip {
      url = "https://github.com/thrombe/unicode-data/archive/d1bc3f78ef53b0f3421a8b378b95a8b00dd69132.tar.gz";
      hash = "sha256-HGDKXRonZoj73AckhJe4t7HqNnvC8jRTJh9aKgChNzs=";
    };
  }
]
